import { Micro } from './micro.model';

export const MICROS_SEED: Micro[] = [
  // ======= Mineralstoffe – Mengenelemente =======
  {
    id: 'kalium',
    name: 'Kalium',
    symbol: 'K',
    category: 'Mineralstoff · Mengenelement',
    unit: 'mg',
    desc: 'Elektrolyt, u. a. wichtig für Blutdruck und Nerven-/Muskel-Funktion.',
    rda: { male: 4000, female: 4000, pregnant: 4000, unit: 'mg' },
    sources: ['OTL Skript 3.3, Mineralstoff-Guide (Kalium)'],
  },
  {
    id: 'kalzium',
    name: 'Kalzium',
    symbol: 'Ca',
    category: 'Mineralstoff · Mengenelement',
    unit: 'mg',
    desc: 'Knochen/Zähne, Signalübertragung, Muskelkontraktion.',
    rda: { male: 1000, female: 1000, pregnant: 1200, unit: 'mg' },
    sources: ['OTL Skript 3.3, Mineralstoff-Guide (Kalzium)'],
  },
  {
    id: 'magnesium',
    name: 'Magnesium',
    symbol: 'Mg',
    category: 'Mineralstoff · Mengenelement',
    unit: 'mg',
    desc: 'Kofaktor für viele Enzyme, Muskel- & Nervenfunktion.',
    rda: { male: 350, female: 300, pregnant: 300, unit: 'mg' },
    sources: ['OTL Skript 3.3, Mineralstoff-Guide (Magnesium)'],
  },
  {
    id: 'natrium',
    name: 'Natrium',
    symbol: 'Na',
    category: 'Mineralstoff · Mengenelement',
    unit: 'mg',
    desc: 'Elektrolyt/Flüssigkeitshaushalt; Hinweis: Salzzufuhr begrenzen.',
    rda: { male: 1500, female: 1500, pregnant: 1500, unit: 'mg' },
    sources: ['OTL Skript 3.3, Mineralstoff-Guide (Natrium)'],
  },
  {
    id: 'phosphor',
    name: 'Phosphor',
    symbol: 'P',
    category: 'Mineralstoff · Mengenelement',
    unit: 'mg',
    desc: 'Enzymaktivierung, Säure-Basen-Haushalt, Knochen/Zähne.',
    rda: { male: 550, female: 550, pregnant: 550, unit: 'mg' },
    sources: ['OTL Skript 3.3, Mineralstoff-Guide (Phosphor)'],
  },
  {
    id: 'chlorid',
    name: 'Chlorid',
    symbol: 'Cl',
    category: 'Mineralstoff · Mengenelement',
    unit: 'mg',
    desc: 'Wichtiges Anion im Elektrolythaushalt.',
    notes: 'Im Skript nur als Mengenelement aufgeführt; keine RDA-Seite.',
    sources: ['OTL Skript 3.3, Mineralstoff-Übersicht'],
  },
  {
    id: 'schwefel',
    name: 'Schwefel',
    symbol: 'S',
    category: 'Mineralstoff · Mengenelement',
    unit: 'mg',
    desc: 'Bestandteil schwefelhaltiger Aminosäuren.',
    notes: 'Im Skript nur in der Übersicht; keine RDA-Seite.',
    sources: ['OTL Skript 3.3, Mineralstoff-Übersicht'],
  },

  // ======= Mineralstoffe – Spurenelemente =======
  {
    id: 'eisen',
    name: 'Eisen',
    symbol: 'Fe',
    category: 'Mineralstoff · Spurenelement',
    unit: 'mg',
    desc: 'Sauerstofftransport (Hämoglobin/Myoglobin).',
    notes:
      'RDA-Seite vorhanden, Zahlen im Skript als Tabelle/Grafik – für DB hier bewusst offen gelassen.',
    sources: ['OTL Skript 3.3, Mineralstoff-Guide (Eisen)'],
  },
  {
    id: 'fluorid',
    name: 'Fluorid',
    symbol: 'F',
    category: 'Mineralstoff · Spurenelement',
    unit: 'mg',
    desc: 'Zahnmineralisation/Kariesprophylaxe.',
    rda: { male: 3.5, female: 3.0, pregnant: 3.0, unit: 'mg' },
    sources: ['OTL Skript 3.3, Mineralstoff-Guide (Fluorid)'],
  },
  {
    id: 'jod',
    name: 'Jod',
    symbol: 'I',
    category: 'Mineralstoff · Spurenelement',
    unit: 'µg',
    desc: 'Schilddrüsenhormone, Stoffwechsel.',
    rda: { male: 200, female: 200, pregnant: 230, unit: 'µg' },
    notes: 'Erwachsene: 180–200 µg/Tag – im Skript als Spanne.',
    sources: ['OTL Skript 3.3, Mineralstoff-Guide (Jod)'],
  },
  {
    id: 'selen',
    name: 'Selen',
    symbol: 'Se',
    category: 'Mineralstoff · Spurenelement',
    unit: 'µg',
    desc: 'Antioxidans, Schilddrüsenhormon-Aktivierung, Immunfunktion.',
    rda: { male: 70, female: 60, pregnant: 60, unit: 'µg' },
    sources: ['OTL Skript 3.3, Mineralstoff-Guide (Selen)'],
  },
  {
    id: 'zink',
    name: 'Zink',
    symbol: 'Zn',
    category: 'Mineralstoff · Spurenelement',
    unit: 'mg',
    desc: 'Immunfunktion, Proteinsynthese, Wundheilung.',
    notes:
      'RDA im Skript als Spanne wegen Phytatgehalt: Männer 11–16 mg, Frauen 7–10 mg, Schwangere 7–13 mg.',
    sources: ['OTL Skript 3.3, Mineralstoff-Guide (Zink)'],
  },
  // (weitere Spurenelemente aus der Übersicht ohne Detailseite:)
  {
    id: 'chrom',
    name: 'Chrom',
    symbol: 'Cr',
    category: 'Mineralstoff · Spurenelement',
    unit: 'µg',
    sources: ['OTL Skript 3.3, Mineralstoff-Übersicht'],
  },
  {
    id: 'kobalt',
    name: 'Kobalt',
    symbol: 'Co',
    category: 'Mineralstoff · Spurenelement',
    unit: 'µg',
    sources: ['OTL Skript 3.3, Mineralstoff-Übersicht'],
  },
  {
    id: 'kupfer',
    name: 'Kupfer',
    symbol: 'Cu',
    category: 'Mineralstoff · Spurenelement',
    unit: 'mg',
    sources: ['OTL Skript 3.3, Mineralstoff-Übersicht'],
  },
  {
    id: 'mangan',
    name: 'Mangan',
    symbol: 'Mn',
    category: 'Mineralstoff · Spurenelement',
    unit: 'mg',
    sources: ['OTL Skript 3.3, Mineralstoff-Übersicht'],
  },
  {
    id: 'molybdaen',
    name: 'Molybdän',
    symbol: 'Mo',
    category: 'Mineralstoff · Spurenelement',
    unit: 'µg',
    sources: ['OTL Skript 3.3, Mineralstoff-Übersicht'],
  },
  {
    id: 'nickel',
    name: 'Nickel',
    symbol: 'Ni',
    category: 'Mineralstoff · Spurenelement',
    unit: 'µg',
    sources: ['OTL Skript 3.3, Mineralstoff-Übersicht'],
  },
  {
    id: 'silizium',
    name: 'Silizium',
    symbol: 'Si',
    category: 'Mineralstoff · Spurenelement',
    unit: 'mg',
    sources: ['OTL Skript 3.3, Mineralstoff-Übersicht'],
  },
  {
    id: 'vanadium',
    name: 'Vanadium',
    symbol: 'V',
    category: 'Mineralstoff · Spurenelement',
    unit: 'µg',
    sources: ['OTL Skript 3.3, Mineralstoff-Übersicht'],
  },
  {
    id: 'zinn',
    name: 'Zinn',
    symbol: 'Sn',
    category: 'Mineralstoff · Spurenelement',
    unit: 'mg',
    sources: ['OTL Skript 3.3, Mineralstoff-Übersicht'],
  },
  {
    id: 'arsen',
    name: 'Arsen',
    symbol: 'As',
    category: 'Mineralstoff · Spurenelement',
    unit: 'µg',
    notes: 'In der Übersicht geführt, ernährungsphysiologisch umstritten.',
    sources: ['OTL Skript 3.3, Mineralstoff-Übersicht'],
  },

  // ======= Vitamine – wasserlöslich =======
  {
    id: 'vitamin-b1',
    name: 'Thiamin (Vitamin B1)',
    symbol: 'B1',
    category: 'Vitamin · wasserlöslich',
    unit: 'mg',
    desc: 'Coenzym im Energiestoffwechsel; Nervensystem.',
    rda: { male: 1.2, female: 1.0, pregnant: 1.3, unit: 'mg' },
    sources: ['OTL Skript 3.3, Vitamin-Guide (Thiamin)'],
  },
  {
    id: 'vitamin-b2',
    name: 'Riboflavin (Vitamin B2)',
    symbol: 'B2',
    category: 'Vitamin · wasserlöslich',
    unit: 'mg',
    desc: 'Bestandteil von Coenzymen; antioxidativ.',
    rda: { male: 1.4, female: 1.1, pregnant: 1.4, unit: 'mg' },
    sources: ['OTL Skript 3.3, Vitamin-Guide (Riboflavin)'],
  },
  {
    id: 'niacin',
    name: 'Niacin (Vitamin B3)',
    symbol: 'B3',
    category: 'Vitamin · wasserlöslich',
    unit: 'mg',
    notes: 'Im Skript aufgeführt; eigene Detailseite nicht vorhanden.',
    sources: ['OTL Skript 3.3, Vitamin-Übersicht'],
  },
  {
    id: 'pantothensaeure',
    name: 'Pantothensäure (Vitamin B5)',
    symbol: 'B5',
    category: 'Vitamin · wasserlöslich',
    unit: 'mg',
    notes: 'Im Skript aufgeführt; eigene Detailseite nicht vorhanden.',
    sources: ['OTL Skript 3.3, Vitamin-Übersicht'],
  },
  {
    id: 'vitamin-b6',
    name: 'Vitamin B6',
    symbol: 'B6',
    category: 'Vitamin · wasserlöslich',
    unit: 'mg',
    notes: 'Im Skript aufgeführt; eigene Detailseite nicht vorhanden.',
    sources: ['OTL Skript 3.3, Vitamin-Übersicht'],
  },
  {
    id: 'biotin',
    name: 'Biotin (Vitamin B7)',
    symbol: 'B7',
    category: 'Vitamin · wasserlöslich',
    unit: 'µg',
    notes: 'Im Skript aufgeführt; eigene Detailseite nicht vorhanden.',
    sources: ['OTL Skript 3.3, Vitamin-Übersicht'],
  },
  {
    id: 'folat',
    name: 'Folat (Vitamin B9 / Folsäure)',
    symbol: 'B9',
    category: 'Vitamin · wasserlöslich',
    unit: 'µg',
    desc: 'DNA/RNA-Bildung, Zellteilung, Hämoglobinsynthese.',
    rda: { male: 300, female: 300, pregnant: 550, unit: 'µg' },
    notes: 'Angabe als Folat-Äquivalent im Skript.',
    sources: ['OTL Skript 3.3, Vitamin-Guide (Folat)'],
  },
  {
    id: 'vitamin-b12',
    name: 'Vitamin B12',
    symbol: 'B12',
    category: 'Vitamin · wasserlöslich',
    unit: 'µg',
    desc: 'Blutbildung, Nervenfunktion, Eiweißstoffwechsel.',
    rda: { male: 4, female: 4, pregnant: 4.5, unit: 'µg' },
    sources: ['OTL Skript 3.3, Vitamin-Guide (B12)'],
  },
  {
    id: 'vitamin-c',
    name: 'Vitamin C',
    symbol: 'C',
    category: 'Vitamin · wasserlöslich',
    unit: 'mg',
    desc: 'Antioxidans, Immunsystem, viele Stoffwechselfunktionen.',
    rda: { male: 110, female: 95, pregnant: 105, unit: 'mg' },
    sources: ['OTL Skript 3.3, Vitamin-Guide (Vitamin C)'],
  },

  // ======= Vitamine – fettlöslich =======
  {
    id: 'vitamin-a',
    name: 'Vitamin A (Retinol/Retinoläquivalente)',
    symbol: 'A',
    category: 'Vitamin · fettlöslich',
    unit: 'µg RÄ',
    desc: 'Sehvorgang, Haut/Schleimhäute, Antioxidans.',
    rda: { male: 850, female: 700, pregnant: 800, unit: 'µg' },
    notes: 'Skript nennt 800–850 µg (m); 1 µg Retinol = 6 µg Beta-Carotin.',
    sources: ['OTL Skript 3.3, Vitamin-Guide (Vitamin A)'],
  },
  {
    id: 'vitamin-d',
    name: 'Vitamin D',
    symbol: 'D',
    category: 'Vitamin · fettlöslich',
    unit: 'IE',
    desc: 'Hormonähnlich: Kalziumhomöostase, Knochen, Immunfunktion.',
    rda: { male: 800, female: 800, pregnant: 4000, unit: 'IE' },
    notes: 'Skript: DGE 800 IE; oft 2000–4000 IE als Zufuhrbereich.',
    sources: ['OTL Skript 3.3, Vitamin-Guide (Vitamin D)'],
  },
  {
    id: 'vitamin-e',
    name: 'Vitamin E',
    symbol: 'E',
    category: 'Vitamin · fettlöslich',
    unit: 'mg',
    desc: 'Antioxidans, Zellstoffwechsel.',
    rda: { male: 14, female: 11.5, pregnant: 13, unit: 'mg' },
    notes: 'Skript gibt Spannen: Männer 12–15 mg; Frauen 11–12 mg.',
    sources: ['OTL Skript 3.3, Vitamin-Guide (Vitamin E)'],
  },
  {
    id: 'vitamin-k',
    name: 'Vitamin K (K1/K2)',
    symbol: 'K',
    category: 'Vitamin · fettlöslich',
    unit: 'µg',
    desc: 'Blutgerinnung, Knochenstoffwechsel, Proteinbildung.',
    rda: { male: 75, female: 62.5, pregnant: 60, unit: 'µg' },
    notes: 'Skript-Spannen: Männer 70–80 µg; Frauen 60–65 µg.',
    sources: ['OTL Skript 3.3, Vitamin-Guide (Vitamin K)'],
  },
];
